# Default values for laa-crown-court-proceeding.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-crown-court-proceeding-dev-ecr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

sentry:
  sampleRate: 0.05

aws_region: eu-west-2

java:
  host_env: test

jwt:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_BEzx6UWw4

maatApi:
  baseUrl: https://maat-cd-api.tst.legalservices.gov.uk/api/internal/v1/assessment
  oauthUrl: https://maat-cd-api-tst.auth.eu-west-2.amazoncognito.com/oauth2/token

cdaApi:
  baseUrl: https://test.court-data-adaptor.service.justice.gov.uk/api/internal/v2
  oauthUrl: https://test.court-data-adaptor.service.justice.gov.uk/oauth/token

evidenceApi:
  baseUrl: http://laa-crime-evidence.laa-crime-evidence-test.svc.cluster.local/api/internal/v1/evidence
  oauthUrl: https://laa-crime-auth-evidence.auth.eu-west-2.amazoncognito.com/oauth2/token

serviceAccount:
  create: false
  annotations: {}
  name: "laa-crown-court-proceeding"

service:
  type: ClusterIP
  port: 80
  targetPort: 8087

ingress:
  whitelist_source_range: "128.77.75.64/26, 18.169.147.172/32, 35.176.93.186/32, 18.130.148.126/32, 35.176.148.126/32, 5.172.196.188, 13.232.220.164, 23.22.2.46, 23.83.129.219, 23.92.127.2, 23.106.37.99, 23.111.152.74, 23.111.159.174, 37.252.231.50, 43.225.198.122, 43.229.84.12, 46.20.45.18, 46.246.122.10, 50.2.185.66, 50.16.153.186, 52.0.204.16, 52.24.42.103, 52.48.244.35, 52.52.34.158, 52.52.95.213, 52.52.118.192, 52.57.132.90, 52.59.46.112, 52.59.147.246, 52.62.12.49, 52.63.142.2, 52.63.164.147, 52.63.167.55, 52.67.148.55, 52.73.209.122, 52.89.43.70, 52.194.115.181, 52.197.31.124, 52.197.224.235, 52.198.25.184, 52.201.3.199, 52.209.34.226, 52.209.186.226, 52.210.232.124, 54.68.48.199, 54.70.202.58, 54.94.206.111, 64.237.49.203, 64.237.55.3, 66.165.229.130, 66.165.233.234, 72.46.130.18, 72.46.131.10, 76.72.167.154, 76.72.172.208, 76.164.234.106, 76.164.234.130, 82.103.136.16, 82.103.139.165, 82.103.145.126, 85.195.116.134, 89.163.146.247, 89.163.242.206, 94.75.211.73, 94.75.211.74, 94.247.174.83, 96.47.225.18, 103.10.197.10, 103.47.211.210, 104.129.24.154, 104.129.30.18, 107.182.234.77, 108.181.70.3, 148.72.170.233, 148.72.171.17, 151.106.52.134, 159.122.168.9, 162.208.48.94, 162.218.67.34, 162.253.128.178, 168.1.203.46, 169.51.2.18, 169.54.70.214, 169.56.174.151, 172.241.112.86, 173.248.147.18, 173.254.206.242, 174.34.156.130, 175.45.132.20, 178.162.206.244, 178.255.152.2, 178.255.153.2, 179.50.12.212, 184.75.208.210, 184.75.209.18, 184.75.210.90, 184.75.210.226, 184.75.214.66, 184.75.214.98, 185.39.146.214, 185.39.146.215, 185.70.76.23, 185.93.3.65, 185.136.156.82, 185.152.65.167, 185.180.12.65, 185.246.208.82, 188.172.252.34, 190.120.230.7, 196.240.207.18, 196.244.191.18, 196.245.151.42, 199.87.228.66, 200.58.101.248, 201.33.21.5, 207.244.80.239, 209.58.139.193, 209.58.139.194, 209.95.50.14, 212.78.83.12, 212.78.83.16"
  environmentName: laa-crown-court-proceeding-test
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
  externalAnnotations: {}
  hosts:
    - host: laa-crown-court-proceeding-test.apps.live.cloud-platform.service.justice.gov.uk
      paths: ["/"]
  tls: []
  className: default

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8096
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5

cloudPlatform:
  aws:
    sqs:
      region: eu-west-2
      queue:
        hearingResulted: crime-apps-test-hearing-resulted-queue
        prosecutionConcluded:
          url: crime-apps-test-prosecution-concluded-queue
          listenerEnabled: true
          scheduleEnabled: true

scheduledDowntime:
  enabled: true
  # Start at 6am UTC Monday-Friday
  startup: '0 6 * * 1-5'
  # Stop at 10pm UTC Monday-Friday
  shutdown: '0 22 * * 1-5'
  serviceAccountName: scheduled-downtime-serviceaccount

scheduledScaling:
  enabled: true
  # Start at 8:15am UTC Monday-Friday
  scaleUp: '15 8 * * 1-5'
  # Stop at 8am UTC Monday-Friday
  scaleDown: '0 8 * * 1-5'

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

emailClient:
  notify_reactivated_prosecution_template_id: 7ca95ad3-6e57-47fe-96e2-eaaf038e64ed
  notify_reactivated_prosecution_recipient: LAACrimeApps@justice.gov.uk
  notify_dropped_prosecution_template_id: 2ce9c2c4-9c87-47f7-9df9-684c14ebc0df
  notify_dropped_prosecution_recipient: LAACrimeApps@justice.gov.uk

cron:
  report_reactivated_cases: '0 5 8 * * *'
  report_dropped_prosecution: '0 10 8 * * *'

logging:
  level: INFO